services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: team-builder
      POSTGRES_USER: snce-exercise
      POSTGRES_PASSWORD: snce-password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://snce-exercise:snce-password@db:5432/team-builder

volumes:
  postgres_data:
